### ISSUE TITLE
ListEndpointsService only supports one direction

### ISSUE THREAD

**Issue by peterbastiani-akkerweb** [DKE-Data/agrirouter-sdk-dotnet-standard#70]
**Describe the bug**
`ListEndpointsUnfilteredService` and `ListEndpointsService` is able to filter on **one** direction only. For example, to retrieve all endpoints which are able to receive data, it is required to call the `ListEndpointsUnfilteredService` or `ListEndpointsService` twice. One call with direction `Receive` and another with direction `SendReceive`.

**Expected behavior**
Get all Receive or Send endpoints in one service call.

**Comment by Frank-Wiebeler** [comment]
Did you check this example implementation in the Test? https://github.com/DKE-Data/agrirouter-sdk-dotnet-standard/blob/develop/agrirouter-api-dotnet-standard-test/Service/Messaging/Http/ListEndpointsServiceTest.cs

There's a SendReceive-Attribute used.

**Comment by peterbastiani-akkerweb** [comment]
> Did you check this example implementation in the Test? https://github.com/DKE-Data/agrirouter-sdk-dotnet-standard/blob/develop/agrirouter-api-dotnet-standard-test/Service/Messaging/Http/ListEndpointsServiceTest.cs
> 
> There's a SendReceive-Attribute used.

I have created this issue as discussed with Sascha.

**Comment by saschadoemer** [comment]
I created the following scenario:

One sender, connected to three endpoints. One is able to send TaskData, one is able to receive TaskData and one is able to send & receive TaskData.

![image](https://user-images.githubusercontent.com/1309344/110252121-2a7a4980-7f84-11eb-89c3-1799c02d319b.png)

![image](https://user-images.githubusercontent.com/1309344/110252137-3960fc00-7f84-11eb-88fc-c04e55558c69.png)

In a second step I created a simple test case, that is listing the endpoints that can be reached by the sender. The expectation was:

1) Filtering for TaskData with direction **send or receive** should list at least 3 endpoints (the one that can send, the one that can receive and the one that can send & receive).

2) Filtering for TaskData with direction **send** should list at least 2 endpoints (the one that can send and the one that can send & receive).

3) Filtering for TaskData with direction **receive** should list at least 2 endpoints (the one that can receive and the one that can send & receive).

You can see the integration test for this scenario within the open PR and have a look at the following commit:

https://github.com/DKE-Data/agrirouter-sdk-dotnet-standard/pull/69/commits/d9513a09f0bc70d3456d295fd643c033ba6fb88e

Since this is - as far as I understood by now - the desired behavior, there would be no need for a custom service filtering those endpoints.
